name: 'Automatically Create Pull Request'

on:
  push:
    branches:
      - '**'
      - '!main'

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Login to GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check if Pull Request already exists
        id: check_pr
        run: |
          PR_EXISTS=$(gh pr list --head "${{ github.head_ref }}" --json number --jq '.[0].number' | head -n 1)
          echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV
          if [[ -z "$PR_EXISTS" ]]; then
            echo "No existing PR for this branch."
            echo "PR_EXISTS=false" >> $GITHUB_ENV
          else
            echo "Existing PR number: $PR_EXISTS"
            echo "PR_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.PR_EXISTS == 'false'
        run: |
          gh pr create --base main --head ${{ github.ref_name }} --title "New Pull Request for ${{ github.ref_name }}" --body "Automatically created PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
